# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 16 Apr 2013 17:53:43 +0000
*               @ALL          0
*               @user         8
